name: monkey_lang
version: 0.9.7
description: Monkey programming language interpreter in Dart.
author: Marc Reichelt <mcreichelt@gmail.com>
homepage: https://github.com/mreichelt/monkey-dart
executables:
  monkey: repl

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
