name: monkey_lang
version: 0.9.6
description: Monkey programming language interpreter in Dart.
author: Marc Reichelt <mcreichelt@gmail.com>
homepage: https://github.com/mreichelt/monkey-dart
executables:
  monkey: repl
dependencies:
dev_dependencies:
  test: ^0.12.18+1
